name: React CI/CD pipeline

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Env Variables
        run: |
          echo -e VITE_KAKAO_CLIENT_ID=${{ secrets.VITE_KAKAO_CLIENT_ID }} >> ".env"
          echo -e VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} >> ".env"
          echo -e VITE_NAVER_CLIENT_ID=${{ secrets.VITE_NAVER_CLIENT_ID }} >> ".env"
          echo -e VITE_FACEBOOK_CLIENT_ID=${{ secrets.VITE_FACEBOOK_CLIENT_ID }} >> ".env"
          echo -e VITE_REDIRECT_URI=${{ secrets.VITE_REDIRECT_URI }} >> ".env"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/Hydrogen
          cache: yarn
      - run: yarn

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: doktalk/doktalk-fe
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
